apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api   
    spec: 
      containers:
        - name: api
          image: igorguimaa/api-bootcamp-k8s-produto:v2
          resources:
            requests:
              memory: "32Mi"
              cpu:  50
            limits:
              memory: "64Mi"
              cpu:  100
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 0
          #   periodSeconds: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   failureThreshold: 1                     
          # readinessProbe:
          #   httpGet:
          #     path: /read
          #     port: 8080
          #   initialDelaySeconds: 0
          #   periodSeconds: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   failureThreshold: 1                               
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://igorguima:XGmcU5bHa@mongodb-service:27017/admin
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
      app: api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort

